name: main branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: cache apt
      uses: actions/cache@v3
      id: cache-apt
      with:
        path: "~/cache-apt"
        key: cache-apt

    - name: install dependencies
      env:
        CACHE_HIT: ${{steps.cache-apt.outputs.cache-hit}}
        MLX_PATH: ./minilibx
      run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/cache-apt/* /
          else
            sudo apt-get update -y && sudo apt-get upgrade -y
            sudo apt-get install gcc make xorg libxext-dev libbsd-dev xvfb valgrind
            mkdir -p ~/cache-apt
            for dep in gcc make xorg libxext-dev libbsd-dev xvfb valgrind libmd-dev libc6-dbg; do
                sudo dpkg -L $dep |
                while IFS= read -r f; do if test -f $f; then echo $f; fi; done |
                sudo xargs cp --parents --target-directory ~/cache-apt/
            done
            cd $MLX_PATH && make && sudo bash ./install
            find /usr/local -type f | grep mlx | sudo xargs cp --parents --target-directory ~/cache-apt/
          fi

    - name: make
      run: make

    - name: run
      env:
        DISPLAY: ":99"
        WINDOW_NAME: "program"
      run: |
        Xvfb $DISPLAY -screen 0 1080x720x24 &
        valgrind -q --error-exitcode=1 --leak-check=full --show-leak-kinds=all --track-origins=yes ./program.out &
        xdotool search --name $WINDOW_NAME windowfocus key Escape